export enum AuditEventType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  USER_REGISTERED = 'USER_REGISTERED',
  EMPLOYEE_REGISTERED = 'EMPLOYEE_REGISTERED',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  TWO_FA_SUCCESS = 'TWO_FA_SUCCESS',
  TWO_FA_FAILED = 'TWO_FA_FAILED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED = 'ACCOUNT_UNLOCKED',
  USER_UPDATED = 'USER_UPDATED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_INVALIDATED = 'TOKEN_INVALIDATED'
}
